### ISSUE TITLE
Render markdown docs

### ISSUE THREAD

**Issue by Vurich** [nrc/cargo-src#246] opened 2018-07-05 09:09 UTC
So I think it'd be cool to show the documentation rendered by default with the option to show it as it appears in the source code. Combined with #245 you could make reading a source file with `cargo src` as nice as reading `rustdoc` output, with the added ability to seamlessly show and navigate the source code.

**Comment by nrc** [comment] 2018-07-06 02:42
I think this would be nice, we'd just have to be careful to keep line numbers accurate.

**Comment by Vurich** [comment] 2018-07-06 11:44
We can just store the line number on the line object

**Comment by matthiasbeyer** [comment] 2018-09-27 09:04
Duplicate of #229 ?

**Closed** 2018-09-27 09:09 UTC
